(()=>{'use strict';const c=document.querySelector('#stage'),x=c.getContext('2d'),status=document.querySelector('#status');
const W=960,H=540,ground=450;const p={x:90,y:ground-58,w:34,h:58,vx:0,vy:0,face:1,on:true,attack:0};const e={x:650,y:ground-50,w:34,h:50,hp:3,hit:0};const input={l:false,r:false,jump:false,atk:false};
const tune={accel:1500,decel:1900,max:260,jump:610,gravity:1750,air:.62,coyote:.10,buffer:.12,jumpCut:.48};let coy=0,buf=0,last=performance.now(),cam=0,won=false;
const hold=(id,k)=>{const b=document.querySelector(id);for(const ev of ['pointerdown'])b.addEventListener(ev,a=>{a.preventDefault();input[k]=true;b.setPointerCapture?.(a.pointerId)});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,a=>{a.preventDefault();input[k]=false})};hold('#left','l');hold('#right','r');hold('#jump','jump');hold('#attack','atk');
addEventListener('keydown',e=>{if(e.code==='KeyA'||e.code==='ArrowLeft')input.l=true;if(e.code==='KeyD'||e.code==='ArrowRight')input.r=true;if(e.code==='Space')input.jump=true;if(e.code==='KeyJ')input.atk=true});addEventListener('keyup',e=>{if(e.code==='KeyA'||e.code==='ArrowLeft')input.l=false;if(e.code==='KeyD'||e.code==='ArrowRight')input.r=false;if(e.code==='Space')input.jump=false;if(e.code==='KeyJ')input.atk=false});
let prevJump=false,prevAtk=false;function approach(v,t,n){return v<t?Math.min(t,v+n):Math.max(t,v-n)}
function step(dt){const dir=(input.r?1:0)-(input.l?1:0),control=p.on?1:tune.air;if(dir){p.face=dir;p.vx=approach(p.vx,dir*tune.max,tune.accel*control*dt)}else p.vx=approach(p.vx,0,tune.decel*control*dt);
if(p.on)coy=tune.coyote;else coy=Math.max(0,coy-dt);if(input.jump&&!prevJump)buf=tune.buffer;else buf=Math.max(0,buf-dt);if(buf>0&&coy>0){p.vy=-tune.jump;p.on=false;buf=0;coy=0}if(!input.jump&&prevJump&&p.vy<0)p.vy*=tune.jumpCut;
p.vy+=tune.gravity*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.y+p.h>=ground){if(!p.on&&p.vy>260)status.textContent='着地 — 次へ';p.y=ground-p.h;p.vy=0;p.on=true}p.x=Math.max(20,Math.min(900,p.x));
if(input.atk&&!prevAtk&&p.attack<=0)p.attack=.22;p.attack=Math.max(0,p.attack-dt);e.hit=Math.max(0,e.hit-dt);if(p.attack>.10&&e.hp>0&&e.hit<=0&&Math.abs((p.x+p.w/2)-(e.x+e.w/2))<70){e.hp--;e.hit=.28;e.x+=p.face*28;status.textContent=e.hp?'命中！':'敵を倒した — 烽火台へ'}
if(e.hp<=0&&p.x>850&&!won){won=true;status.textContent='到達！ もう一度走りたくなるか？'}cam=Math.max(0,Math.min(240,p.x-300));prevJump=input.jump;prevAtk=input.atk}
function draw(){x.clearRect(0,0,W,H);x.fillStyle='#18211e';x.fillRect(0,0,W,H);x.fillStyle='#27372f';for(let i=0;i<7;i++){x.beginPath();x.moveTo(i*180-cam*.25,H);x.lineTo(i*180+100-cam*.25,250);x.lineTo(i*180+240-cam*.25,H);x.fill()}x.fillStyle='#55452e';x.fillRect(0,ground,W,90);x.fillStyle='#79633f';x.fillRect(0,ground,W,5);
x.fillStyle='#6f5b3c';x.fillRect(340-cam,ground-42,90,42);x.fillRect(500-cam,ground-82,105,82);x.fillStyle='#c49a55';x.fillRect(885-cam,ground-130,18,130);x.beginPath();x.arc(894-cam,ground-145,18,0,7);x.fill();
if(e.hp>0){x.save();x.translate(e.x-cam,e.y);if(e.hit)x.translate((Math.random()-.5)*8,0);x.fillStyle='#713f35';x.fillRect(0,0,e.w,e.h);x.fillStyle='#ddd';x.fillRect(7,8,5,5);x.restore()}
x.save();x.translate(p.x-cam,p.y);x.fillStyle='#d0c3a2';x.fillRect(0,0,p.w,p.h);x.fillStyle='#3d4a45';x.fillRect(5,18,24,30);if(p.attack>0){x.strokeStyle='#f0d18a';x.lineWidth=6;x.beginPath();x.moveTo(p.face>0?30:4,25);x.lineTo(p.face>0?72:-38,8);x.stroke()}x.restore()}
function loop(t){const dt=Math.min(.033,(t-last)/1000);last=t;step(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop)})();